language: python
python:
   - "3.6"
  
before_install:
 - set -e

notifications:
  email:
    on_success: change
    on_failure: change

env:
 - RELEASE=master

install:
 - sudo apt-get install opus-tools
 - sudo pip install --upgrade pip
 - pip install -r requirements.txt

# command to run tests
script:
 - set -e
 - export basedir=`pwd`
 
 # AHOTTS
 - cd $basedir
 - hostname -I
 - hostname -i
 - git clone https://github.com/stts-se/AhoTTS-eu-Wikispeech.git
 - cd AhoTTS-eu-Wikispeech
 - git checkout $RELEASE || echo "No such release for ahotts. Using master."
 - sh script_compile_all_linux.sh && mkdir -p txt wav
 - sh start_ahotts_wikispeech.sh &
 - export ahotts_pid=$!
 - echo "ahotts started with pid $ahotts_pid"
 - sleep 5
 - python ahotts_testcall.py "test call for ahotts"
 - sh .travis/exit_server_and_fail_if_not_running.sh ahotts $ahotts_pid
